CharacterTrait.register("hikitraits:selective_eater")
CharacterTrait.register("hikitraits:animal_lover")
CharacterTrait.register("hikitraits:exercise_routine")
CharacterTrait.register("hikitraits:road_tripper")
CharacterTrait.register("hikitraits:panic_fumbling")
CharacterTrait.register("hikitraits:thrill_seeker")
CharacterTrait.register("hikitraits:loud_when_hurt")
CharacterTrait.register("hikitraits:skipped_leg_day")
CharacterTrait.register("hikitraits:task_fixation")
CharacterTrait.register("hikitraits:exhaustion_anxiety")
CharacterTrait.register("hikitraits:weight_anxiety")
CharacterTrait.register("hikitraits:meditate")
CharacterTrait.register("hikitraits:high_spirits")
CharacterTrait.register("hikitraits:shrug_it_off")
CharacterTrait.register("hikitraits:comfort_eater")
CharacterTrait.register("hikitraits:bitten_no")
CharacterTrait.register("hikitraits:neck_reflex")
CharacterTrait.register("hikitraits:meat_fueled")


